package dugsolutions.leaf.v35.player.decision.learned.wisp

enum class WispPlayFeature {
    BIAS, ACTION_HOLD, ACTION_PLAY, PHASE_CULTIVATION, PHASE_BATTLE,
    GAME_PROGRESS, ROUNDS_REMAINING, BATTLES_REMAINING, FINAL_BATTLE,
    SUPPORT_PASS, MAIN_ACTIONS_REMAINING, SELF_VP, RELATIVE_VP,
    SELF_WISP_COUNT, WISP_END_GAME_VP, WISP_DECK_REMAINING,
    SELF_DICE_COUNT, SELF_DICE_POWER, SELF_HAND_POWER, SELF_PLANT_COUNT,
    SELF_WATER, SELF_SUNLIGHT, SELF_MULCH, SELF_BEES, SELF_WORMS,
    BATTLE_TOTAL_DEFICIT, BATTLE_WOUND_RISK_ROWS, BATTLE_WINNING_ROWS,
    HUMAN_REFERENCE_MATCH
}
