package dugsolutions.leaf.v30.chronicle.domain

enum class WarningType {
    MISSING_WORM,
    BATTLE_HAND_DICE_COUNT_NOT_THREE,
    UNKNOWN_EFFECT,
    REROLL_TARGET_MISSING,
    REROLL_DIE_NOT_FOUND,
    RAISE_TARGET_MISSING,
    RAISE_DIE_NOT_FOUND,
    DOUBLE_MATCHING_DICE_INVALID_TARGET,
    UPGRADE_TARGET_MISSING,
    UPGRADE_DIE_NOT_FOUND,
    UPGRADE_DIE_UNAVAILABLE,
    FLIP_TARGET_MISSING,
    FLIP_DIE_NOT_FOUND
}
