package dugsolutions.leaf.cards.domain

enum class CardEffect(
    val description: String,
) {
    ADD_TO_DIE("Add VALUE to one die, without exceeding MAX"),
    ADD_TO_TOTAL("Add VALUE to final total"),
    ADJUST_BY("Adjust any die by +/- VALUE, without exceeding 1 or MAX"),
    ADJUST_TO_MAX("Adjust VALUE dice to MAX"),
    ADJUST_TO_MIN_OR_MAX("Adjust VALUE dice to either MIN or MAX"),
    ADORN("Play card to Floral Array then draw a card."),
    DEFLECT("Deflects VALUE"),
    DISCARD("Opponent discards VALUE dice or cards"),
    DISCARD_CARD("Opponent discards VALUE cards"),
    DISCARD_DIE("Opponent discards VALUE dice"),
    DRAW_CARD("Draw VALUE cards"),
    DRAW_CARD_COMPOST("Draw VALUE cards from Compost"),
    DRAW_DIE("Draw VALUE lowest-sided dice"),
    DRAW_DIE_ANY("Draw VALUE dice from Supply"),
    DRAW_DIE_COMPOST("Draw VALUE lowest-sided dice from Compost."),
    DRAW("Draw VALUE cards or dice."),
    FLOURISH_OVERRIDE("Override the Flourish type for this turn"),
    GAIN_FREE_ROOT("Gain a free Root card"),
    GAIN_FREE_CANOPY("Gain a free Canopy card"),
    GAIN_FREE_VINE("Gain a free Vine card"),
    REDUCE_COST_ROOT("Reduce the cost of a Root card by VALUE"),
    REDUCE_COST_CANOPY("Reduce the cost of a Canopy card by VALUE"),
    REDUCE_COST_VINE("Reduce the cost of a Vine card by VALUE"),
    REROLL_ACCEPT_2ND("Reroll VALUE dice, you must accept the second roll"),
    REROLL_ALL_MAX("Force an opponent to reroll a MAX value die"),
    REROLL_TAKE_BETTER("Reroll VALUE dice, you may take the better of the two rolls"),
    REPLAY_VINE("May use VALUE vine effect again immediately"),
    RETAIN_CARD("Retain VALUE cards"),
    RETAIN_DIE("Retain VALUE die"),
    RETAIN_DIE_REROLL("Retain VALUE dice with reroll"),
    REUSE_CARD("Reuse VALUE cards"),
    REUSE_DIE("Reuse VALUE dice, do not reroll"),
    REUSE_DIE_REROLL("Reuse VALUE dice, rerolling"),
    REUSE_ANY("Reuse VALUE cards or dice"),
    UPGRADE_ANY_RETAIN("Upgrade VALUE dice then use. (D12 -> D20 costs 8)"),
    UPGRADE_ANY("Upgrade VALUE dice then discard. (D12 -> D20 costs 8)"),
    UPGRADE_D4("Upgrade a D4 and retain"),
    UPGRADE_D6("Upgrade a D4 or D6 and retain"),
    UPGRADE_D8("Upgrade up to a D8 and retain"),
    UPGRADE_D10("Upgrade up to a D10 and retain"),
    USE_OPPONENT_CARD("Use opponent's canopy or root cards"),
    USE_OPPONENT_DIE("Use VALUE of opponent's dice")
} 
