package dugsolutions.leaf.v35.player.decision.learned.cultivation

/** Stable standard feature vocabulary for learned Cultivation Main policies. */
enum class CultivationMainFeature {
    BIAS,

    // Visible state.
    GAME_PROGRESS,
    CULTIVATION_ROUNDS_REMAINING,
    BATTLE_ROUNDS_REMAINING,
    BATTLE_NEXT,
    MAIN_ACTIONS_REMAINING,
    SELF_DICE_COUNT,
    SELF_DICE_POWER,
    SELF_HAND_DICE_COUNT,
    SELF_PURCHASING_POWER,
    SELF_AFFORDABLE_TIER,
    SELF_PLANT_COUNT,
    SELF_FACE_UP_PLANT_COUNT,
    SELF_FACE_DOWN_PLANT_COUNT,
    SELF_BEE_COUNT,
    SELF_WORM_COUNT,
    SELF_WATER_COUNT,
    SELF_MULCH_COUNT,
    SELF_SUNLIGHT_COUNT,
    SELF_BUTTERFLY_COUNT,
    GROVE_BEE_COUNT,
    GROVE_WORM_COUNT,
    GROVE_WATER_COUNT,
    GROVE_MULCH_COUNT,
    GROVE_SUNLIGHT_COUNT,
    GROVE_BUTTERFLY_COUNT,

    // Candidate identity.
    ACTION_DRAW,
    ACTION_PLANT,
    ACTION_ROUND_EFFECT_1,
    ACTION_ROUND_EFFECT_2,
    ACTION_DONE,
    ACTION_ROOT,
    ACTION_VINE,
    ACTION_FLOWER,
    ACTION_COST,

    // Draw candidate descriptors.
    DRAW_NEXT_DIE_SIDES,
    DRAW_EXPECTED_ROLL,
    DRAW_ROLL_REWARD_CHANCE,

    // Simple action/state interactions. Global state by itself is constant across
    // candidates, so these interactions let the linear policy respond to context.
    ACTION_DRAW_BATTLE_NEXT,
    ACTION_PLANT_BATTLE_NEXT,
    ACTION_ROUND_BATTLE_NEXT,
    ACTION_DRAW_BATTLES_REMAINING,
    ACTION_PLANT_BATTLES_REMAINING,
    ACTION_ROUND_BATTLES_REMAINING,
    ACTION_DRAW_CULTIVATION_REMAINING,
    ACTION_PLANT_CULTIVATION_REMAINING,
    ACTION_ROUND_CULTIVATION_REMAINING,
    ACTION_DRAW_MAIN_ACTIONS_REMAINING,
    ACTION_PLANT_MAIN_ACTIONS_REMAINING,
    ACTION_ROUND_MAIN_ACTIONS_REMAINING
}
