package dugsolutions.leaf.v35.player.decision.learned.mulch

enum class MulchTargetFeature {
    BIAS,
    DIE_FACE,
    DIE_SIDES,
    DIE_FACE_FRACTION,
    DIE_EXPECTED_REROLL,
    DIE_REROLL_GAIN,
    DIE_HEADROOM,
    IS_LOWEST_FACE,
    IS_HIGHEST_FACE,
    IS_LOWEST_SIDED,
    IS_HIGHEST_SIDED,
    HAND_COUNT,
    HAND_FACE_TOTAL,
    HAND_FACE_TOTAL_AFTER,
    HAND_SIDES_TOTAL,
    PURCHASE_TIER_STEPS_LOST,
    PURCHASE_BEST_TIER_LOSS,
    BATTLE_NEXT,
    CULTIVATION_ROUNDS_REMAINING,
    BATTLES_REMAINING,
    STORED_MULCH_COUNT,
    STORED_MULCH_SIDES_TOTAL,
    STORED_MULCH_MAX_SIDES,
    HUMAN_REFERENCE_MATCH
}
