JAR=../../../bin/runnable-texturepacker.jar
INPUT=../android/assets/texture-originals/
OUTPUT=../android/assets/texture
PACKNAME=pack

all:
	java -cp ${JAR} com.badlogic.gdx.tools.texturepacker.TexturePacker ${INPUT} ${OUTPUT} ${PACKNAME}
